In [2]:
import pandas as pd

print(pd.__version__)

3.0.5

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import openpyxl

print("Toutes les bibliothèques fonctionnent.")

Matplotlib is building the font cache; this may take a moment.

Toutes les bibliothèques fonctionnent.

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_excel("../data/raw/DATA_PFE_balanced.xlsx")

In [7]:
df.shape

(8141, 10)

In [8]:
df.columns

Index(['ticket_id', 'État', 'ID de phase', 'Priorité', 'Titre de la demande',
       'Demandé pour Nom', 'Date MAJ ', 'Date de résolution',
       'Date/Heure de création', 'Categorie'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8141 entries, 0 to 8140
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ticket_id               8141 non-null   int64
 1   État                    7579 non-null   str
 2   ID de phase             7584 non-null   str
 3   Priorité                7584 non-null   str
 4   Titre de la demande     8141 non-null   str
 5   Demandé pour Nom        8141 non-null   str
 6   Date MAJ                7584 non-null   datetime64[us]
 7   Date de résolution      5624 non-null   datetime64[us]
 8   Date/Heure de création  8141 non-null   datetime64[us]
 9   Categorie               8141 non-null   str
dtypes: datetime64[us](3), int64(1), str(6)
memory usage: 636.1 KB

In [10]:
df.isnull().sum()

ticket_id                    0
État                       562
ID de phase                557
Priorité                   557
Titre de la demande          0
Demandé pour Nom             0
Date MAJ                   557
Date de résolution        2517
Date/Heure de création       0
Categorie                    0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.describe(include="all")

,ticket_id,État,ID de phase,Priorité,Titre de la demande,Demandé pour Nom,Date MAJ,Date de résolution,Date/Heure de création,Categorie
count,8141.000000,7579,7584,7584,8141,8141,7584,5624,8141,8141
unique,NaN,8,9,4,124,1895,NaN,NaN,NaN,9
top,NaN,Assignée,Fulfill,Faible (P4),Demande de service,Hafsa Benkirane,NaN,NaN,NaN,Assistance & Demandes generales
freq,NaN,4158,4883,6942,6408,12,NaN,NaN,NaN,7686
mean,8456.163493,NaN,NaN,NaN,NaN,NaN,2025-04-20 18:41:40.284398,2025-04-07 19:50:24.984109,2025-03-14 09:20:47.419765,NaN
min,3.000000,NaN,NaN,NaN,NaN,NaN,2023-01-04 23:50:17.353000,2023-01-04 08:34:59,2023-01-02 14:13:16.755000,NaN
25%,5108.000000,NaN,NaN,NaN,NaN,NaN,2024-12-03 20:39:04.502750,2024-11-02 18:27:03.750000,2024-10-03 12:17:30.882000,NaN
50%,9581.000000,NaN,NaN,NaN,NaN,NaN,2025-05-03 17:34:06.456000,2025-05-05 20:45:08.500000,2025-04-14 10:43:22.527000,NaN
75%,11841.000000,NaN,NaN,NaN,NaN,NaN,2026-01-25 19:09:17.128750,2026-01-30 11:32:58.135000,2026-01-07 17:36:56.794000,NaN
max,14170.000000,NaN,NaN,NaN,NaN,NaN,2026-03-26 08:25:43.798000,2026-05-12 06:55:32,2026-03-26 16:04:31,NaN
std,4071.939346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df["État"].value_counts(dropna=False)

État
Assignée                     4158
Attente utilisateur final    1635
En cours                     1605
NaN                           562
Rejeté                         85
Attente fournisseur            62
Ouverte                        16
Rouverte                       16
Terminé                         2
Name: count, dtype: int64

In [14]:
df["Priorité"].value_counts(dropna=False)

Priorité
Faible (P4)      6942
NaN               557
Moyenne (P3)      479
Critique (P1)     114
Élevée (P2)        49
Name: count, dtype: int64

In [15]:
df["ID de phase"].value_counts(dropna=False)

ID de phase
Fulfill             4883
Escalate            1428
Accept              1055
NaN                  557
Abandon               85
FirstLineSupport      80
Classify              24
Review                17
Approve                8
Log                    4
Name: count, dtype: int64

In [16]:
df["Categorie"].value_counts(dropna=False)

Categorie
Assistance & Demandes generales         7686
Gestion des comptes et mots de passe     312
Materiel informatique                     68
SAP & Applications metier                 21
Messagerie & Office 365                   19
Autre                                     19
Logiciels & Applications                  10
Reseau & Connectivite                      5
Securite informatique                      1
Name: count, dtype: int64

In [22]:
for col in df.columns:
    print(repr(col))

'ticket_id'
'État'
'ID de phase'
'Priorité'
'Titre de la demande'
'Demandé pour Nom'
'Date MAJ '
'Date de résolution'
'Date/Heure de création'
'Categorie'

In [25]:
df[["Date/Heure de création", "Date de résolution", "Date MAJ"]].describe()

,Date/Heure de création,Date de résolution,Date MAJ
count,8141,5624,7584
mean,2025-03-14 09:20:47.419765,2025-04-07 19:50:24.984109,2025-04-20 18:41:40.284398
min,2023-01-02 14:13:16.755000,2023-01-04 08:34:59,2023-01-04 23:50:17.353000
25%,2024-10-03 12:17:30.882000,2024-11-02 18:27:03.750000,2024-12-03 20:39:04.502750
50%,2025-04-14 10:43:22.527000,2025-05-05 20:45:08.500000,2025-05-03 17:34:06.456000
75%,2026-01-07 17:36:56.794000,2026-01-30 11:32:58.135000,2026-01-25 19:09:17.128750
max,2026-03-26 16:04:31,2026-05-12 06:55:32,2026-03-26 08:25:43.798000

In [26]:
mask = (
    df["Date de résolution"].notna()
    & (df["Date de résolution"] < df["Date/Heure de création"])
)

mask.sum()

np.int64(0)

In [27]:
mask_maj = (
    df["Date MAJ"].notna()
    & (df["Date MAJ"] < df["Date/Heure de création"])
)

mask_maj.sum()

np.int64(0)

In [28]:
missing = pd.DataFrame({
    "Valeurs_manquantes": df.isna().sum(),
    "Pourcentage": (df.isna().mean() * 100).round(2)
})

missing

                        Valeurs_manquantes  Pourcentage
ticket_id                                0         0.00
État                                   562         6.90
ID de phase                            557         6.84
Priorité                               557         6.84
Titre de la demande                      0         0.00
Demandé pour Nom                         0         0.00
Date MAJ                               557         6.84
Date de résolution                    2517        30.92
Date/Heure de création                   0         0.00
Categorie                                0         0.00

In [29]:
df["ticket_id"].duplicated().sum()

np.int64(0)

In [30]:
df["État"].value_counts(dropna=False)

État
Assignée                     4158
Attente utilisateur final    1635
En cours                     1605
NaN                           562
Rejeté                         85
Attente fournisseur            62
Ouverte                        16
Rouverte                       16
Terminé                         2
Name: count, dtype: int64

In [31]:
df["Priorité"].value_counts(dropna=False)

Priorité
Faible (P4)      6942
NaN               557
Moyenne (P3)      479
Critique (P1)     114
Élevée (P2)        49
Name: count, dtype: int64

In [32]:
df["ID de phase"].value_counts(dropna=False)

ID de phase
Fulfill             4883
Escalate            1428
Accept              1055
NaN                  557
Abandon               85
FirstLineSupport      80
Classify              24
Review                17
Approve                8
Log                    4
Name: count, dtype: int64

In [33]:
df["Categorie"].value_counts(dropna=False)

Categorie
Assistance & Demandes generales         7686
Gestion des comptes et mots de passe     312
Materiel informatique                     68
SAP & Applications metier                 21
Messagerie & Office 365                   19
Autre                                     19
Logiciels & Applications                  10
Reseau & Connectivite                      5
Securite informatique                      1
Name: count, dtype: int64

In [34]:
mask = (
    df["Date de résolution"].notna()
    & (df["Date de résolution"] < df["Date/Heure de création"])
)

mask.sum()

np.int64(0)

In [35]:
mask_maj = (
    df["Date MAJ"].notna()
    & (df["Date MAJ"] < df["Date/Heure de création"])
)

mask_maj.sum()

np.int64(0)

In [36]:
df[df["État"].isna()].head(20)

,ticket_id,État,ID de phase,Priorité,Titre de la demande,Demandé pour Nom,Date MAJ,Date de résolution,Date/Heure de création,Categorie
32,48,NaN,NaN,NaN,Demande de service,Youssef El Ouali,NaT,2023-09-09 01:03:12,2023-08-17 09:47:17,Assistance & Demandes generales
72,132,NaN,NaN,NaN,Demande de service,Adil Benkirane,NaT,2023-03-10 04:57:53,2023-03-07 09:05:13,Assistance & Demandes generales
74,134,NaN,NaN,NaN,Demande de service,Rim Alaoui,NaT,NaT,2024-04-21 15:38:01,Assistance & Demandes generales
75,141,NaN,NaN,NaN,Demande de service,Noura Hajji,NaT,2023-11-24 09:12:26,2023-11-23 13:21:17,Assistance & Demandes generales
77,144,NaN,NaN,NaN,Demande de service,Ahmed Tahiri,NaT,2023-11-21 22:01:14,2023-11-15 11:48:21,Assistance & Demandes generales
79,147,NaN,NaN,NaN,Demande de service,Siham Chraibi,NaT,2025-01-12 13:42:05,2025-01-05 12:38:16,Assistance & Demandes generales
80,154,NaN,NaN,NaN,Demande de service,Malak Bouhaddou,NaT,2023-07-27 23:55:41,2023-07-26 13:17:29,Assistance & Demandes generales
82,157,NaN,NaN,NaN,Demande de service,Hafsa Sebti,NaT,2024-03-08 01:44:02,2024-03-05 17:17:44,Assistance & Demandes generales
83,167,NaN,NaN,NaN,Demande de service,Houda Bouhaddou,NaT,NaT,2024-10-06 11:41:31,Assistance & Demandes generales
84,168,NaN,NaN,NaN,Demande de service,Rachid Hajji,NaT,NaT,2025-03-21 16:29:09,Assistance & Demandes generales
85,185,NaN,NaN,NaN,Demande de service,Mustapha Tahiri,NaT,NaT,2023-01-07 11:32:48,Assistance & Demandes generales
86,193,NaN,NaN,NaN,Demande de service,Laila Mansouri,NaT,NaT,2025-09-27 09:07:59,Assistance & Demandes generales
87,194,NaN,NaN,NaN,Demande de service,Loubna El Bakkali,NaT,2025-01-15 04:44:35,2025-01-13 12:15:03,Assistance & Demandes generales
88,204,NaN,NaN,NaN,Demande de service,Loubna Bensalah,NaT,NaT,2025-02-03 14:57:33,Assistance & Demandes generales
89,205,NaN,NaN,NaN,Demande de service,Ikram Alaoui,NaT,2025-07-30 21:30:33,2025-07-13 10:15:14,Assistance & Demandes generales
90,206,NaN,NaN,NaN,Demande de service,Mustapha Ait Ahmed,NaT,2023-05-20 03:13:48,2023-05-12 12:01:37,Assistance & Demandes generales
91,209,NaN,NaN,NaN,Demande de service,Said Mansouri,NaT,2023-05-05 00:38:35,2023-05-01 11:04:57,Assistance & Demandes generales
92,213,NaN,NaN,NaN,Demande de service,Jamal Kettani,NaT,2024-05-05 01:56:18,2024-05-02 11:42:31,Assistance & Demandes generales
93,214,NaN,NaN,NaN,Demande de service,Youssef El Khatib,NaT,2024-03-22 10:18:00,2024-03-14 15:08:46,Assistance & Demandes generales
94,215,NaN,NaN,NaN,Demande de service,Imane Ouazzani,NaT,2026-03-18 12:54:39,2026-03-15 15:30:15,Assistance & Demandes generales

In [37]:
df[df["État"].isna()]["Date de résolution"].isna().value_counts()

Date de résolution
False    365
True     197
Name: count, dtype: int64

In [38]:
df[df["Priorité"].isna()][
    ["ticket_id", "État", "ID de phase",
     "Date MAJ", "Date de résolution"]
].head(20)

    ticket_id État ID de phase Date MAJ  Date de résolution
32         48  NaN         NaN      NaT 2023-09-09 01:03:12
72        132  NaN         NaN      NaT 2023-03-10 04:57:53
74        134  NaN         NaN      NaT                 NaT
75        141  NaN         NaN      NaT 2023-11-24 09:12:26
77        144  NaN         NaN      NaT 2023-11-21 22:01:14
79        147  NaN         NaN      NaT 2025-01-12 13:42:05
80        154  NaN         NaN      NaT 2023-07-27 23:55:41
82        157  NaN         NaN      NaT 2024-03-08 01:44:02
83        167  NaN         NaN      NaT                 NaT
84        168  NaN         NaN      NaT                 NaT
85        185  NaN         NaN      NaT                 NaT
86        193  NaN         NaN      NaT                 NaT
87        194  NaN         NaN      NaT 2025-01-15 04:44:35
88        204  NaN         NaN      NaT                 NaT
89        205  NaN         NaN      NaT 2025-07-30 21:30:33
90        206  NaN         NaN      NaT 2023-05-20 03:13:48
91        209  NaN         NaN      NaT 2023-05-05 00:38:35
92        213  NaN         NaN      NaT 2024-05-05 01:56:18
93        214  NaN         NaN      NaT 2024-03-22 10:18:00
94        215  NaN         NaN      NaT 2026-03-18 12:54:39

In [39]:
df[df["Priorité"].isna()].index.equals(
    df[df["ID de phase"].isna()].index
)

True

In [41]:
df_557 = df[df["Priorité"].isna()]

df_557[
    [
        "ticket_id",
        "État",
        "Titre de la demande",
        "Demandé pour Nom",
        "Date de résolution",
        "Date/Heure de création",
        "Categorie"
    ]
].head(30)

,ticket_id,État,Titre de la demande,Demandé pour Nom,Date de résolution,Date/Heure de création,Categorie
32,48,NaN,Demande de service,Youssef El Ouali,2023-09-09 01:03:12,2023-08-17 09:47:17,Assistance & Demandes generales
72,132,NaN,Demande de service,Adil Benkirane,2023-03-10 04:57:53,2023-03-07 09:05:13,Assistance & Demandes generales
74,134,NaN,Demande de service,Rim Alaoui,NaT,2024-04-21 15:38:01,Assistance & Demandes generales
75,141,NaN,Demande de service,Noura Hajji,2023-11-24 09:12:26,2023-11-23 13:21:17,Assistance & Demandes generales
77,144,NaN,Demande de service,Ahmed Tahiri,2023-11-21 22:01:14,2023-11-15 11:48:21,Assistance & Demandes generales
79,147,NaN,Demande de service,Siham Chraibi,2025-01-12 13:42:05,2025-01-05 12:38:16,Assistance & Demandes generales
80,154,NaN,Demande de service,Malak Bouhaddou,2023-07-27 23:55:41,2023-07-26 13:17:29,Assistance & Demandes generales
82,157,NaN,Demande de service,Hafsa Sebti,2024-03-08 01:44:02,2024-03-05 17:17:44,Assistance & Demandes generales
83,167,NaN,Demande de service,Houda Bouhaddou,NaT,2024-10-06 11:41:31,Assistance & Demandes generales
84,168,NaN,Demande de service,Rachid Hajji,NaT,2025-03-21 16:29:09,Assistance & Demandes generales
85,185,NaN,Demande de service,Mustapha Tahiri,NaT,2023-01-07 11:32:48,Assistance & Demandes generales
86,193,NaN,Demande de service,Laila Mansouri,NaT,2025-09-27 09:07:59,Assistance & Demandes generales
87,194,NaN,Demande de service,Loubna El Bakkali,2025-01-15 04:44:35,2025-01-13 12:15:03,Assistance & Demandes generales
88,204,NaN,Demande de service,Loubna Bensalah,NaT,2025-02-03 14:57:33,Assistance & Demandes generales
89,205,NaN,Demande de service,Ikram Alaoui,2025-07-30 21:30:33,2025-07-13 10:15:14,Assistance & Demandes generales
90,206,NaN,Demande de service,Mustapha Ait Ahmed,2023-05-20 03:13:48,2023-05-12 12:01:37,Assistance & Demandes generales
91,209,NaN,Demande de service,Said Mansouri,2023-05-05 00:38:35,2023-05-01 11:04:57,Assistance & Demandes generales
92,213,NaN,Demande de service,Jamal Kettani,2024-05-05 01:56:18,2024-05-02 11:42:31,Assistance & Demandes generales
93,214,NaN,Demande de service,Youssef El Khatib,2024-03-22 10:18:00,2024-03-14 15:08:46,Assistance & Demandes generales
94,215,NaN,Demande de service,Imane Ouazzani,2026-03-18 12:54:39,2026-03-15 15:30:15,Assistance & Demandes generales
96,217,NaN,Demande de service,Amine Lahlou,2025-09-05 03:37:25,2025-08-26 13:12:06,Assistance & Demandes generales
98,223,NaN,Demande de service,Houda Benomar,NaT,2023-04-21 17:41:41,Assistance & Demandes generales
100,235,NaN,Demande de service,Hamid Benali,2026-02-02 11:05:56,2026-02-01 10:03:41,Assistance & Demandes generales
101,237,NaN,Demande de service,Najat Squalli,2024-04-29 14:48:39,2024-04-29 10:26:31,Assistance & Demandes generales
102,238,NaN,Demande de service,Khalid Berrada,NaT,2025-09-12 11:55:25,Assistance & Demandes generales
123,276,NaN,Demande de service,Hassan El Amrani,2025-03-12 10:02:51,2025-03-10 11:59:50,Assistance & Demandes generales
124,277,NaN,Demande de service,Youssef Belkadi,NaT,2025-07-20 11:27:44,Assistance & Demandes generales
132,300,NaN,Demande de service,Hafsa Ait Ahmed,NaT,2023-05-05 12:03:03,Assistance & Demandes generales
137,313,NaN,Demande de service,Chaimae Berrada,NaT,2025-12-23 10:03:32,Assistance & Demandes generales
138,320,NaN,Demande de service,Nisrine Alaoui,NaT,2025-04-06 10:56:36,Assistance & Demandes generales

In [42]:
df_557["État"].value_counts(dropna=False)

État
NaN    557
Name: count, dtype: int64

In [43]:
df_557["Categorie"].value_counts(dropna=False)

Categorie
Assistance & Demandes generales    557
Name: count, dtype: int64

In [44]:
df_557["Date de résolution"].isna().value_counts()

Date de résolution
False    361
True     196
Name: count, dtype: int64

In [45]:
df_557["Date de résolution"].notna().sum()

np.int64(361)

In [46]:
df_557["Date de résolution"].isna().sum()

np.int64(196)

In [48]:
df_clean = df.copy()

In [49]:
df_clean.columns = df_clean.columns.str.strip()

In [50]:
df_clean["État"] = df_clean["État"].fillna("Inconnu")

In [51]:
df_clean["Priorité"] = df_clean["Priorité"].fillna("Inconnu")

In [52]:
df_clean["ID de phase"] = df_clean["ID de phase"].fillna("Inconnu")

In [53]:
df_clean.isna().sum()

ticket_id                    0
État                         0
ID de phase                  0
Priorité                     0
Titre de la demande          0
Demandé pour Nom             0
Date MAJ                   557
Date de résolution        2517
Date/Heure de création       0
Categorie                    0
dtype: int64

In [54]:
print(df_clean["État"].value_counts(dropna=False))

État
Assignée                     4158
Attente utilisateur final    1635
En cours                     1605
Inconnu                       562
Rejeté                         85
Attente fournisseur            62
Ouverte                        16
Rouverte                       16
Terminé                         2
Name: count, dtype: int64

In [55]:
print(df_clean["Priorité"].value_counts(dropna=False))

Priorité
Faible (P4)      6942
Inconnu           557
Moyenne (P3)      479
Critique (P1)     114
Élevée (P2)        49
Name: count, dtype: int64

In [56]:
print(df_clean["ID de phase"].value_counts(dropna=False))

ID de phase
Fulfill             4883
Escalate            1428
Accept              1055
Inconnu              557
Abandon               85
FirstLineSupport      80
Classify              24
Review                17
Approve                8
Log                    4
Name: count, dtype: int64

In [57]:
df_clean["Temps_resolution_heures"] = (
    df_clean["Date de résolution"]
    - df_clean["Date/Heure de création"]
).dt.total_seconds() / 3600

In [58]:
df_clean[
    [
        "ticket_id",
        "Date/Heure de création",
        "Date de résolution",
        "Temps_resolution_heures"
    ]
].head(20)

,ticket_id,Date/Heure de création,Date de résolution,Temps_resolution_heures
0,3,2026-02-10 13:55:26.031,2026-02-13 14:20:20.000,72.414991
1,4,2026-03-03 09:57:49.939,NaT,NaN
2,5,2025-09-23 17:16:53.268,NaT,NaN
3,6,2026-02-06 16:08:36.542,2026-02-13 20:13:48.000,172.086516
4,7,2026-02-06 16:06:12.849,2026-02-20 06:03:17.000,325.951153
5,8,2026-03-03 10:16:36.847,NaT,NaN
6,9,2025-11-29 19:31:37.933,2025-12-06 03:53:29.000,152.364185
7,10,2026-02-10 13:58:45.989,2026-02-11 02:03:25.000,12.077503
8,11,2026-03-24 17:59:39.501,2026-03-25 15:45:26.483,21.763051
9,12,2026-03-25 17:03:58.932,2026-03-30 06:49:39.000,109.761130
10,15,2026-03-24 09:45:50.037,2026-03-24 16:00:07.834,6.238277
11,20,2026-03-18 11:45:57.975,2026-03-22 09:36:14.000,93.837785
12,21,2026-03-24 15:20:36.657,2026-03-24 16:36:05.536,1.258022
13,24,2026-03-24 21:39:24.855,2026-04-03 22:47:16.000,241.130874
14,26,2026-03-16 16:00:52.550,NaT,NaN
15,27,2024-02-29 07:35:48.797,2024-03-03 21:26:12.000,85.839779
16,28,2023-12-13 09:59:47.476,2023-12-14 12:33:09.438,26.556101
17,29,2025-07-15 12:26:25.966,NaT,NaN
18,30,2025-10-14 18:15:30.191,NaT,NaN
19,31,2025-07-15 09:33:25.846,2025-07-17 04:05:20.000,42.531709

In [62]:
df_clean.to_csv(
    "../data/processed/tickets_clean.csv",
    index=False
)

In [63]:
import os

print(os.path.exists("../data/processed/tickets_clean.csv"))

True

In [47]:
df[df["État"].isna() & df["Priorité"].isna()].shape[0]

557

In [40]:
df[df["Date MAJ"].isna()].index.equals(
    df[df["Priorité"].isna()].index
)

True

In [23]:
df.columns = df.columns.str.strip()

In [24]:
for col in df.columns:
    print(repr(col))

'ticket_id'
'État'
'ID de phase'
'Priorité'
'Titre de la demande'
'Demandé pour Nom'
'Date MAJ'
'Date de résolution'
'Date/Heure de création'
'Categorie'

In [6]:
df.head()

,ticket_id,État,ID de phase,Priorité,Titre de la demande,Demandé pour Nom,Date MAJ,Date de résolution,Date/Heure de création,Categorie
0,3,En cours,Fulfill,Faible (P4),Demande de service,Ayman El Idrissi,2026-03-18 09:18:55.978,2026-02-13 14:20:20,2026-02-10 13:55:26.031,Assistance & Demandes generales
1,4,Attente utilisateur final,Fulfill,Faible (P4),Demande de service,Widad Tahiri,2026-03-12 10:17:36.423,NaT,2026-03-03 09:57:49.939,Assistance & Demandes generales
2,5,Attente utilisateur final,Fulfill,Moyenne (P3),Demande de service,Hassan Belkadi,2026-02-20 09:19:59.298,NaT,2025-09-23 17:16:53.268,Assistance & Demandes generales
3,6,Attente utilisateur final,Fulfill,Faible (P4),Demande de service,Loubna Benjelloun,2026-03-25 11:11:14.946,2026-02-13 20:13:48,2026-02-06 16:08:36.542,Assistance & Demandes generales
4,7,Attente utilisateur final,Fulfill,Faible (P4),Demande de service,Aziz Berrada,2026-03-11 15:15:59.620,2026-02-20 06:03:17,2026-02-06 16:06:12.849,Assistance & Demandes generales