In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(
    r"C:\Users\DEV\Desktop\Intelligent-Helpdesk-Analytics\data\processed\tickets_clean.csv"
)

In [4]:
df_ml = df[df["Priorité"] != "Inconnu"].copy()

In [5]:
df_sla = df_ml[df_ml["Temps_resolution_heures"].notna()].copy()

In [6]:
df_sla.shape

(5263, 11)

In [7]:
df_sla["SLA_cible_heures"] = df_sla["Priorité"].map({
    "Critique (P1)": 3,
    "Élevée (P2)": 8,
    "Moyenne (P3)": 64,
    "Faible (P4)": 90
})

In [8]:
df_sla["SLA_depasse"] = (
    df_sla["Temps_resolution_heures"] > df_sla["SLA_cible_heures"]
).astype(int)

In [9]:
df_sla["SLA_depasse"].value_counts()

SLA_depasse
0    3565
1    1698
Name: count, dtype: int64

In [10]:
X = df_sla[[
    "Priorité",
    "Categorie",
    "Titre de la demande"
]]

y = df_sla["SLA_depasse"]

In [11]:
X.head()

      Priorité                        Categorie Titre de la demande
0  Faible (P4)  Assistance & Demandes generales  Demande de service
3  Faible (P4)  Assistance & Demandes generales  Demande de service
4  Faible (P4)  Assistance & Demandes generales  Demande de service
6  Faible (P4)  Assistance & Demandes generales  Demande de service
7  Faible (P4)  Assistance & Demandes generales  Demande de service

In [12]:
y.value_counts()

SLA_depasse
0    3565
1    1698
Name: count, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [14]:
categorical_features = [
    "Priorité",
    "Categorie",
    "Titre de la demande"
]

In [15]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [17]:
print("X_train :", X_train.shape)
print("X_test  :", X_test.shape)
print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)

X_train : (4210, 3)
X_test  : (1053, 3)
y_train : (4210,)
y_test  : (1053,)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [19]:
model_lr = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000))
])

In [20]:
model_lr.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Priorité', 'Categorie',
                                                   'Titre de la demande'])])),
                ('model', LogisticRegression(max_iter=1000))])

In [21]:
y_pred_lr = model_lr.predict(X_test)

In [22]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [23]:
print("Accuracy :", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall   :", recall_score(y_test, y_pred_lr))
print("F1-score :", f1_score(y_test, y_pred_lr))

Accuracy : 0.6885090218423552
Precision: 0.7307692307692307
Recall   : 0.05588235294117647
F1-score : 0.10382513661202186

In [24]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.69      0.99      0.81       713
           1       0.73      0.06      0.10       340

    accuracy                           0.69      1053
   macro avg       0.71      0.52      0.46      1053
weighted avg       0.70      0.69      0.58      1053

In [25]:
cm = confusion_matrix(y_test, y_pred_lr)

print(cm)

[[706   7]
 [321  19]]

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
model_rf = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    ))
])

In [28]:
model_rf.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Priorité', 'Categorie',
                                                   'Titre de la demande'])])),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=200, random_state=42))])

In [29]:
y_pred_rf = model_rf.predict(X_test)

In [30]:
print("Accuracy :", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall   :", recall_score(y_test, y_pred_rf))
print("F1-score :", f1_score(y_test, y_pred_rf))

Accuracy : 0.6400759734093068
Precision: 0.4247104247104247
Recall   : 0.3235294117647059
F1-score : 0.3672787979966611

In [31]:
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.71      0.79      0.75       713
           1       0.42      0.32      0.37       340

    accuracy                           0.64      1053
   macro avg       0.57      0.56      0.56      1053
weighted avg       0.62      0.64      0.63      1053

In [32]:
cm_rf = confusion_matrix(y_test, y_pred_rf)

print(cm_rf)

[[564 149]
 [230 110]]

In [33]:
weights = [
    "balanced",
    {0: 1, 1: 1.5},
    {0: 1, 1: 2},
    {0: 1, 1: 3}
]

In [34]:
results = []

for weight in weights:

    model = Pipeline([
        ("preprocessor", preprocessor),
        ("model", RandomForestClassifier(
            n_estimators=200,
            random_state=42,
            class_weight=weight
        ))
    ])

    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    results.append({
        "class_weight": str(weight),
        "accuracy": accuracy_score(y_test, pred),
        "precision": precision_score(y_test, pred),
        "recall": recall_score(y_test, pred),
        "f1": f1_score(y_test, pred)
    })

In [35]:
results_df = pd.DataFrame(results)

results_df

     class_weight  accuracy  precision    recall        f1
0        balanced  0.640076   0.424710  0.323529  0.367279
1  {0: 1, 1: 1.5}  0.671415   0.475000  0.167647  0.247826
2    {0: 1, 1: 2}  0.639126   0.423077  0.323529  0.366667
3    {0: 1, 1: 3}  0.327635   0.323755  0.994118  0.488439

In [36]:
model_rf_balanced = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    ))
])

model_rf_balanced.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Priorité', 'Categorie',
                                                   'Titre de la demande'])])),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=200, random_state=42))])

In [37]:
y_proba = model_rf_balanced.predict_proba(X_test)[:, 1]

In [38]:
thresholds = [0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60]

threshold_results = []

for threshold in thresholds:

    y_pred_threshold = (y_proba >= threshold).astype(int)

    threshold_results.append({
        "threshold": threshold,
        "accuracy": accuracy_score(y_test, y_pred_threshold),
        "precision": precision_score(y_test, y_pred_threshold),
        "recall": recall_score(y_test, y_pred_threshold),
        "f1": f1_score(y_test, y_pred_threshold)
    })

In [39]:
threshold_df = pd.DataFrame(threshold_results)

threshold_df

   threshold  accuracy  precision    recall        f1
0       0.30  0.325736   0.323473  0.997059  0.488473
1       0.35  0.325736   0.323473  0.997059  0.488473
2       0.40  0.326686   0.323445  0.994118  0.488087
3       0.45  0.328585   0.322705  0.982353  0.485818
4       0.50  0.640076   0.424710  0.323529  0.367279
5       0.55  0.671415   0.474576  0.164706  0.244541
6       0.60  0.682811   0.551724  0.094118  0.160804

In [40]:
FINAL_THRESHOLD = 0.35

y_pred_final = (y_proba >= FINAL_THRESHOLD).astype(int)

In [41]:
print("Accuracy :", accuracy_score(y_test, y_pred_final))
print("Precision:", precision_score(y_test, y_pred_final))
print("Recall   :", recall_score(y_test, y_pred_final))
print("F1-score :", f1_score(y_test, y_pred_final))

Accuracy : 0.32573599240265905
Precision: 0.3234732824427481
Recall   : 0.9970588235294118
F1-score : 0.4884726224783862

In [42]:
cm_final = confusion_matrix(y_test, y_pred_final)

print(cm_final)

[[  4 709]
 [  1 339]]

In [43]:
print(classification_report(y_test, y_pred_final))

              precision    recall  f1-score   support

           0       0.80      0.01      0.01       713
           1       0.32      1.00      0.49       340

    accuracy                           0.33      1053
   macro avg       0.56      0.50      0.25      1053
weighted avg       0.65      0.33      0.17      1053

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [45]:
categorical_features = [
    "Priorité",
    "Categorie"
]

text_feature = "Titre de la demande"

In [46]:
preprocessor_tfidf = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "text",
            TfidfVectorizer(
                max_features=1000,
                ngram_range=(1, 2),
                min_df=2
            ),
            text_feature
        )
    ]
)

In [47]:
model_rf_tfidf = Pipeline([
    ("preprocessor", preprocessor_tfidf),
    ("model", RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    ))
])

In [48]:
model_rf_tfidf.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Priorité', 'Categorie']),
                                                 ('text',
                                                  TfidfVectorizer(max_features=1000,
                                                                  min_df=2,
                                                                  ngram_range=(1,
                                                                               2)),
                                                  'Titre de la demande')])),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=200, random_state=42))])

In [49]:
y_pred_tfidf = model_rf_tfidf.predict(X_test)

In [50]:
print("Accuracy :", accuracy_score(y_test, y_pred_tfidf))
print("Precision:", precision_score(y_test, y_pred_tfidf))
print("Recall   :", recall_score(y_test, y_pred_tfidf))
print("F1-score :", f1_score(y_test, y_pred_tfidf))

Accuracy : 0.6410256410256411
Precision: 0.4269230769230769
Recall   : 0.3264705882352941
F1-score : 0.37

In [51]:
print(confusion_matrix(y_test, y_pred_tfidf))

[[564 149]
 [229 111]]

In [53]:
from sklearn.ensemble import HistGradientBoostingClassifier

In [54]:
model_lr_tfidf = Pipeline([
    ("preprocessor", preprocessor_tfidf),
    ("model", LogisticRegression(
        max_iter=2000,
        class_weight="balanced"
    ))
])

In [55]:
model_lr_tfidf.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Priorité', 'Categorie']),
                                                 ('text',
                                                  TfidfVectorizer(max_features=1000,
                                                                  min_df=2,
                                                                  ngram_range=(1,
                                                                               2)),
                                                  'Titre de la demande')])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=2000))])

In [56]:
y_pred_lr_tfidf = model_lr_tfidf.predict(X_test)

In [57]:
print("Accuracy :", accuracy_score(y_test, y_pred_lr_tfidf))
print("Precision:", precision_score(y_test, y_pred_lr_tfidf))
print("Recall   :", recall_score(y_test, y_pred_lr_tfidf))
print("F1-score :", f1_score(y_test, y_pred_lr_tfidf))

Accuracy : 0.6353276353276354
Precision: 0.417910447761194
Recall   : 0.32941176470588235
F1-score : 0.3684210526315789

In [59]:
import joblib

In [61]:
import os

os.makedirs("../output", exist_ok=True)

In [62]:
joblib.dump(
    model_rf_tfidf,
    "../output/model_sla_rf_tfidf.pkl"
)

['../output/model_sla_rf_tfidf.pkl']

In [63]:
os.path.exists("../output/model_sla_rf_tfidf.pkl")

True

In [58]:
print(confusion_matrix(y_test, y_pred_lr_tfidf))

[[557 156]
 [228 112]]

In [52]:
print(classification_report(y_test, y_pred_tfidf))

              precision    recall  f1-score   support

           0       0.71      0.79      0.75       713
           1       0.43      0.33      0.37       340

    accuracy                           0.64      1053
   macro avg       0.57      0.56      0.56      1053
weighted avg       0.62      0.64      0.63      1053